ROOM_HEADERS={"authority": "chatgpt5free.com",
		"path": "/wp-json/mwai-ui/v1/chats/submit",
		"scheme": "https",
		"accept": "*/*",
		"accept-encoding": "gzip, deflate, br",
		"accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
		"content-type": "application/json",
		"origin": "https://chatgpt5free.com",
		"referer": "https://chatgpt5free.com/chatgpt-5-free/",
		"sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"",
		"sec-ch-ua-mobile": "?0",
		"sec-ch-ua-platform": "Windows",
		"sec-fetch-dest": "empty",
		"sec-fetch-mode": "cors",
		"sec-fetch-site": "same-origin",
		"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
		'x-wp-nonce': '73e2407183'
	}
GPT3_HEADERS = {
  "authority": "api.binjie.fun",
  "method": "POST",
  "path": "/api/generateStream",
  "scheme": "https",
  "accept": "application/json, text/plain, */*",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
  "content-type": "application/json",
  "origin": "https://chat18.aichatos8.com",
  "referer": "https://chat18.aichatos8.com/",
  "sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"",
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": "Windows",
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "cross-site",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
}